// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, created) VALUES (?, ?) RETURNING id, created
`

type CreateSessionParams struct {
	ID      int64
	Created int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.ID, arg.Created)
	var i Session
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, created FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
