// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Deck struct {
	GameID    int64
	SessionID sql.NullString
	Created   string
	Cards     string
	Size      sql.NullInt64
}

type Game struct {
	ID      int64
	Code    string
	Created string
}

type GameSession struct {
	GameID    int64
	SessionID string
	Role      int64
	Created   string
}

type Session struct {
	ID      string
	Created string
}
